
const GameConstants = {
    // Score
	GAME_START_SCORE:            366,
	SCORE_LOSS_DRACULA_TURN:       1,
	SCORE_LOSS_HUNTER_HOSPITAL:    6,
	SCORE_LOSS_VAMPIRE_MATURES:   13,
    
	// Hunters' Health
	GAME_START_HUNTER_LIFE_POINTS: 9,
	LIFE_LOSS_TRAP_ENCOUNTER:      2,
	LIFE_LOSS_DRACULA_ENCOUNTER:   4,
	LIFE_GAIN_REST:                3,
    
	// Dracula's Health
	GAME_START_BLOOD_POINTS:      40,
	LIFE_LOSS_HUNTER_ENCOUNTER:   10,
	LIFE_LOSS_SEA:                 2,
	LIFE_GAIN_CASTLE_DRACULA:     10,
};

const NUM_PLAYERS = 5;
const TRAIL_SIZE  = 6;

const PlayerID = {
	LORD_GODALMING: 0,
	DR_SEWARD:      1,
	VAN_HELSING:    2,
	MINA_HARKER:    3,
	DRACULA:        4,
};

const LocationID = {
    // Legitimate Locations
	ADRIATIC_SEA:             0,
    ALICANTE:                 1,
    AMSTERDAM:                2,
    ATHENS:                   3,
    ATLANTIC_OCEAN:           4,
    BARCELONA:                5,
    BARI:                     6,
    BAY_OF_BISCAY:            7,
    BELGRADE:                 8,
    BERLIN:                   9,
    BLACK_SEA:               10,
    BORDEAUX:                11,
    BRUSSELS:                12,
    BUCHAREST:               13,
    BUDAPEST:                14,
    CADIZ:                   15,
    CAGLIARI:                16,
    CASTLE_DRACULA:          17,
    CLERMONT_FERRAND:        18,
    COLOGNE:                 19,
    CONSTANTA:               20,
    DUBLIN:                  21,
    EDINBURGH:               22,
    ENGLISH_CHANNEL:         23,
    FLORENCE:                24,
    FRANKFURT:               25,
    GALATZ:                  26,
    GALWAY:                  27,
    GENEVA:                  28,
    GENOA:                   29,
    GRANADA:                 30,
    HAMBURG:                 31,
    IONIAN_SEA:              32,
    IRISH_SEA:               33,
    KLAUSENBURG:             34,
    LE_HAVRE:                35,
    LEIPZIG:                 36,
    LISBON:                  37,
    LIVERPOOL:               38,
    LONDON:                  39,
    MADRID:                  40,
    MANCHESTER:              41,
    MARSEILLES:              42,
    MEDITERRANEAN_SEA:       43,
    MILAN:                   44,
    MUNICH:                  45,
    NANTES:                  46,
    NAPLES:                  47,
    NORTH_SEA:               48,
    NUREMBURG:               49,
    PARIS:                   50,
    PLYMOUTH:                51,
    PRAGUE:                  52,
    ROME:                    53,
    SALONICA:                54,
    SANTANDER:               55,
    SARAGOSSA:               56,
    SARAJEVO:                57,
    SOFIA:                   58,
    ST_JOSEPH_AND_ST_MARYS:  59,
    STRASBOURG:              60,
    SWANSEA:                 61,
    SZEGED:                  62,
    TOULOUSE:                63,
    TYRRHENIAN_SEA:          64,
    VALONA:                  65,
    VARNA:                   66,
    VENICE:                  67,
    VIENNA:                  68,
    ZAGREB:                  69,
    ZURICH:                  70,
    
    FIRST_LOCATION:           0,
    LAST_LOCATION:           70,
    
    // Not Actual Locations
    CITY_UNKNOWN:           100,
    SEA_UNKNOWN:            101,
    HIDE:                   102,
    DOUBLE_BACK_1:          103,
    DOUBLE_BACK_2:          104,
    DOUBLE_BACK_3:          105,
    DOUBLE_BACK_4:          106,
    DOUBLE_BACK_5:          107,
    TELEPORT:               108,
    UNKNOWN_LOCATION:        -1,
    NOWHERE:                 -1,
}

const ActionID = {
    REVIVE:              1,
    TRAP_ENCOUNTER:      2,
    VAMPIRE_ENCOUNTER:   3,
    DRACULA_ENCOUNTER:   4,
    HOSPITALISED:        5,
    REST:                6,
    RESEARCH:            7,

    TRAP_MALFUNCTION:    8,
    VAMPIRE_MATURATION:  9,
    PLACE_TRAP:         10,
    SPAWN_VAMPIRE:      11,
    TAKE_SEA_DAMAGE:    12,
    REGENERATE:         13,
}
