
const LocationType = {
	INLAND_CITY: 0,
	PORT_CITY:   1,
	SEA:         2,
};

const LOCATIONS = [
	{"id":  0, "abbrev": "AS", "type": 2, "name": "Adriatic Sea"},
	{"id":  1, "abbrev": "AL", "type": 1, "name": "Alicante"},
	{"id":  2, "abbrev": "AM", "type": 1, "name": "Amsterdam"},
	{"id":  3, "abbrev": "AT", "type": 1, "name": "Athens"},
	{"id":  4, "abbrev": "AO", "type": 2, "name": "Atlantic Ocean"},
	{"id":  5, "abbrev": "BA", "type": 1, "name": "Barcelona"},
	{"id":  6, "abbrev": "BI", "type": 1, "name": "Bari"},
	{"id":  7, "abbrev": "BB", "type": 2, "name": "Bay of Biscay"},
	{"id":  8, "abbrev": "BE", "type": 0, "name": "Belgrade"},
	{"id":  9, "abbrev": "BR", "type": 0, "name": "Berlin"},
	{"id": 10, "abbrev": "BS", "type": 2, "name": "Black Sea"},
	{"id": 11, "abbrev": "BO", "type": 1, "name": "Bordeaux"},
	{"id": 12, "abbrev": "BU", "type": 0, "name": "Brussels"},
	{"id": 13, "abbrev": "BC", "type": 0, "name": "Bucharest"},
	{"id": 14, "abbrev": "BD", "type": 0, "name": "Budapest"},
	{"id": 15, "abbrev": "CA", "type": 1, "name": "Cadiz"},
	{"id": 16, "abbrev": "CG", "type": 1, "name": "Cagliari"},
	{"id": 17, "abbrev": "CD", "type": 0, "name": "Castle Dracula"},
	{"id": 18, "abbrev": "CF", "type": 0, "name": "Clermont-Ferrand"},
	{"id": 19, "abbrev": "CO", "type": 0, "name": "Cologne"},
	{"id": 20, "abbrev": "CN", "type": 1, "name": "Constanta"},
	{"id": 21, "abbrev": "DU", "type": 1, "name": "Dublin"},
	{"id": 22, "abbrev": "ED", "type": 1, "name": "Edinburgh"},
	{"id": 23, "abbrev": "EC", "type": 2, "name": "English Channel"},
	{"id": 24, "abbrev": "FL", "type": 0, "name": "Florence"},
	{"id": 25, "abbrev": "FR", "type": 0, "name": "Frankfurt"},
	{"id": 26, "abbrev": "GA", "type": 0, "name": "Galatz"},
	{"id": 27, "abbrev": "GW", "type": 1, "name": "Galway"},
	{"id": 28, "abbrev": "GE", "type": 0, "name": "Geneva"},
	{"id": 29, "abbrev": "GO", "type": 1, "name": "Genoa"},
	{"id": 30, "abbrev": "GR", "type": 0, "name": "Granada"},
	{"id": 31, "abbrev": "HA", "type": 1, "name": "Hamburg"},
	{"id": 32, "abbrev": "IO", "type": 2, "name": "Ionian Sea"},
	{"id": 33, "abbrev": "IR", "type": 2, "name": "Irish Sea"},
	{"id": 34, "abbrev": "KL", "type": 0, "name": "Klausenburg"},
	{"id": 35, "abbrev": "LE", "type": 1, "name": "Le Havre"},
	{"id": 36, "abbrev": "LI", "type": 0, "name": "Leipzig"},
	{"id": 37, "abbrev": "LS", "type": 1, "name": "Lisbon"},
	{"id": 38, "abbrev": "LV", "type": 1, "name": "Liverpool"},
	{"id": 39, "abbrev": "LO", "type": 1, "name": "London"},
	{"id": 40, "abbrev": "MA", "type": 0, "name": "Madrid"},
	{"id": 41, "abbrev": "MN", "type": 0, "name": "Manchester"},
	{"id": 42, "abbrev": "MR", "type": 1, "name": "Marseilles"},
	{"id": 43, "abbrev": "MS", "type": 2, "name": "Mediterranean Sea"},
	{"id": 44, "abbrev": "MI", "type": 0, "name": "Milan"},
	{"id": 45, "abbrev": "MU", "type": 0, "name": "Munich"},
	{"id": 46, "abbrev": "NA", "type": 1, "name": "Nantes"},
	{"id": 47, "abbrev": "NP", "type": 1, "name": "Naples"},
	{"id": 48, "abbrev": "NS", "type": 2, "name": "North Sea"},
	{"id": 49, "abbrev": "NU", "type": 0, "name": "Nuremberg"},
	{"id": 50, "abbrev": "PA", "type": 0, "name": "Paris"},
	{"id": 51, "abbrev": "PL", "type": 1, "name": "Plymouth"},
	{"id": 52, "abbrev": "PR", "type": 0, "name": "Prague"},
	{"id": 53, "abbrev": "RO", "type": 1, "name": "Rome"},
	{"id": 54, "abbrev": "SA", "type": 1, "name": "Salonica"},
	{"id": 55, "abbrev": "SN", "type": 1, "name": "Santander"},
	{"id": 56, "abbrev": "SR", "type": 0, "name": "Saragossa"},
	{"id": 57, "abbrev": "SJ", "type": 0, "name": "Sarajevo"},
	{"id": 58, "abbrev": "SO", "type": 0, "name": "Sofia"},
	{"id": 59, "abbrev": "JM", "type": 0, "name": "St Joseph and St Marys"},
	{"id": 60, "abbrev": "ST", "type": 0, "name": "Strasbourg"},
	{"id": 61, "abbrev": "SW", "type": 1, "name": "Swansea"},
	{"id": 62, "abbrev": "SZ", "type": 0, "name": "Szeged"},
	{"id": 63, "abbrev": "TO", "type": 0, "name": "Toulouse"},
	{"id": 64, "abbrev": "TS", "type": 2, "name": "Tyrrhenian Sea"},
	{"id": 65, "abbrev": "VA", "type": 1, "name": "Valona"},
	{"id": 66, "abbrev": "VR", "type": 1, "name": "Varna"},
	{"id": 67, "abbrev": "VE", "type": 1, "name": "Venice"},
	{"id": 68, "abbrev": "VI", "type": 0, "name": "Vienna"},
	{"id": 69, "abbrev": "ZA", "type": 0, "name": "Zagreb"},
	{"id": 70, "abbrev": "ZU", "type": 0, "name": "Zurich"}
];
